### ISSUE TITLE
Installation problem when processing fusepy dependency

### ISSUE THREAD

**Issue by yotommy** [etactica/mqtt-malaria#21]
Installation dies when processing fusepy dependency:

```
$ git rev-parse HEAD
b24244676ebe32f9dfef074f84d65fe02fff96f5
$ sudo python setup.py install
Password:
running install
running bdist_egg
running egg_info
writing requirements to mqtt_malaria.egg-info/requires.txt
writing mqtt_malaria.egg-info/PKG-INFO
writing top-level names to mqtt_malaria.egg-info/top_level.txt
writing dependency_links to mqtt_malaria.egg-info/dependency_links.txt
reading manifest file 'mqtt_malaria.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mqtt_malaria.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/__init__.py -> build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/bridge.py -> build/bdist.macosx-10.6-intel/egg/beem
creating build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/cmds/__init__.py -> build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/cmds/keygen.py -> build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/cmds/publish.py -> build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/cmds/subscribe.py -> build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/cmds/watch.py -> build/bdist.macosx-10.6-intel/egg/beem/cmds
copying build/lib/beem/listen.py -> build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/load.py -> build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/main.py -> build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/msgs.py -> build/bdist.macosx-10.6-intel/egg/beem
copying build/lib/beem/trackers.py -> build/bdist.macosx-10.6-intel/egg/beem
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/bridge.py to bridge.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/cmds/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/cmds/keygen.py to keygen.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/cmds/publish.py to publish.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/cmds/subscribe.py to subscribe.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/cmds/watch.py to watch.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/listen.py to listen.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/load.py to load.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/main.py to main.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/msgs.py to msgs.pyc
byte-compiling build/bdist.macosx-10.6-intel/egg/beem/trackers.py to trackers.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.6-intel/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO/scripts
copying build/scripts-2.7/malaria -> build/bdist.macosx-10.6-intel/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.6-intel/egg/EGG-INFO/scripts/malaria to 755
copying mqtt_malaria.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying mqtt_malaria.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying mqtt_malaria.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying mqtt_malaria.egg-info/not-zip-safe -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying mqtt_malaria.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying mqtt_malaria.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
creating 'dist/mqtt_malaria-0.1_75_gb242446-py2.7.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing mqtt_malaria-0.1_75_gb242446-py2.7.egg
removing '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mqtt_malaria-0.1_75_gb242446-py2.7.egg' (and everything under it)
creating /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mqtt_malaria-0.1_75_gb242446-py2.7.egg
Extracting mqtt_malaria-0.1_75_gb242446-py2.7.egg to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Adding mqtt-malaria 0.1-75-gb242446 to easy-install.pth file
Installing malaria script to /Library/Frameworks/Python.framework/Versions/2.7/bin

Installed /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mqtt_malaria-0.1_75_gb242446-py2.7.egg
Processing dependencies for mqtt-malaria==0.1-75-gb242446
Searching for fusepy
Reading http://pypi.python.org/simple/fusepy/
Best match: fusepy 2.0.2
Downloading https://pypi.python.org/packages/source/f/fusepy/fusepy-2.0.2.tar.gz#md5=8db99bcf4854411a9954da976d3bcc5a
Processing fusepy-2.0.2.tar.gz
Running fusepy-2.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SE39QN/fusepy-2.0.2/egg-dist-tmp-OxGeyk
error: README: No such file or directory
$ malaria 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/malaria", line 4, in <module>
    import pkg_resources
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2603, in <module>
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: fusepy
```

**Comment by oedemis** [comment]
any ideas?

**Comment by karlp** [comment]
@oedemis at least, have you got some updated logs?

**Comment by evnix** [comment]
same issue here on centOS 7!
tried installing fusepy too.

**Comment by oedemis** [comment]
I tried the following steps
$ virtualenv my_env
$ . myenv/bin/activate
(my_env) $ pip install -e .

=> malaria publish -h
then i have ..
Traceback (most recent call last):
  File /Users/<...>/mqtt-malaria/my_env/bin/malaria", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/<...>/mqtt-malaria/malaria", line 30, in <module>
    import beem.main
  File "/Users/<...>/mqtt-malaria/beem/main.py", line 34, in <module>
    import beem.cmds
  File "/Users/<...>/mqtt-malaria/beem/cmds/__init__.py", line 2, in <module>
    import beem.cmds.subscribe
  File "/Users/<...>/mqtt-malaria/beem/cmds/subscribe.py", line 34, in <module>
    import beem.listen
  File "/Users/<...>/mqtt-malaria/beem/listen.py", line 40, in <module>
    import fuse
  File "/Users/<...>/mqtt-malaria/my_env/lib/python2.7/site-packages/fuse.py", line 69, in <module>
    raise EnvironmentError('Unable to find libfuse')
EnvironmentError: Unable to find libfuse

pip freeze says:

fusepy==2.0.2
mosquitto==1.2.3
-e git+https://github.com/remakeelectric/mqtt-malaria.git@f9374ac8e5c01b0b140d71727e0759ced249a37d#egg=mqtt_malaria-master
wheel==0.24.0

**Comment by karlp** [comment]
I suspect that the fusepy package dependencies are wrong then.  I have system installed "fuse" and "fuse-libs" on fedora.

Also, did you see the comment https://github.com/remakeelectric/mqtt-malaria/issues/21#issuecomment-37933182 that works around this?  If you can work out what fusepy is doing wrong then I'm happy to merge it, but there's very little else I can do that I can see.

**Comment by flaviostutz** [comment]
I did "apt-get install fuse" on ubuntu and it worked!

**Comment by flaviostutz** [comment]
Another way is using a container. Try mine: 
docker run flaviostutz/mqtt-malaria publish -P 8 -n 10000 -H mqtt.example.org -s 100

**Comment by pikachuabc** [comment]
For error:' Getting EnvironmentError: Unable to find libfuse ' under macOS
Download fuse at https://osxfuse.github.io/ and install it.
Problem solved. However I don't know what is fuse and how it works.= =

**Comment by karlp** [comment]
As best I can tell, this is an OSX only problem and you just need to install fuse externall first, before fusepy can do it's thing.  I'm closing this unless there's anything someone thinks there's something to do especially here.
